spring:
  application:
    name: saleUserBe
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://qubiton.xyz:33010/newU300_dev?serverTimezone=Asia/Seoul
    username: root
    password: asdf1234
  security:
    user:
      name: user
      password: asdf1234!@




