server:
  port: 11001
  tomcat:
    max-http-form-post-size: 1024MB
    max-swallow-size: 1024MB

spring:
  application:
    name: saleUserBe
  profiles:
    default: local

  # security
  security:
    user:
      name: user
      password: asdf1234!@

  # multipart/form-data
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB

  jpa:
    properties:
      hibernate:
        # batch fetch size
        default_batch_fetch_size: 1000
        format_sql: false
    # OSIV
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false

decorator:
  datasource:
    p6spy:
      enable-logging: true

# log
logging:
  config: classpath:logback-spring.xml
  file:
    path: app/logs
  level:
    p6spy: info
    org.hibernate.SQL: off
# jwt
jwt:
  secret-key: sale-2025-delivery+1004kksale-2025-delivery+1004kksale-2025-delivery+1004kk
  issuer-uri: www.hotDelivery.com
  accessToken-expired-time: 3600000
  refreshToken-expired-time: 86400000

# file path
file:
  path: /Users/i***REMOVED***/Desktop/uploads/

# kakao
kakao:
  restapi-key: 017f314b795d2d84aacac0877a1d58ec
  redirect-uri: http://localhost:3001

# naver
naver:
  client-id: i3siOwKjlSwl_cWH6A1E
  client-secret: 17aWKxirW8