server:
  ssl:
    enabled: true
    key-store: file:/cert/keystore.p12
    key-store-type: PKCS12
    key-store-password: example
spring:
  application:
    name: saleUserBe
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/discount?serverTimezone=Asia/Seoul
    username: root
    password: password

  # security
  security:
    user:
      name: user
      password: asdf1234!@
  hikari:
    connection-timeout: 60000
    maximum-pool-size: 12
    minimum-idle: 5
    idle-timeout: 300000
    max-lifetime: 6000000

  jpa:
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

# swagger
springdoc:
  api-docs:
    path: /user-dev/user/v3/api-docs
  swagger-ui:
    path: /user-dev/user/swagger-ui/index.html
    url: /user-dev/user/v3/api-docs

# file path
file:
  path: example
